version: '3.8'

services:
  # redis:
  #   image: docker.io/bitnami/redis:6.2
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #   ports:
  #     - '6379:6379'
  #   volumes:
  #     - redis_data:/bitnami/redis/data
  # postgres:
  #   image: postgres:14.1-alpine
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - '5432:5432'
  #   volumes: 
  #     - data:/var/lib/postgresql/data
  rocksdb:
    image: panasun/rocksdb:v8.1.1
      # context: .
      # dockerfile: Dockerfile
      
    

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
  redis_data:
    driver: local
